### ISSUE TITLE
typings install with Exit status 1

### ISSUE THREAD

**Issue by JacosNet** [morocarlo/ng2-my-datepicker#2]
Here npm logs:
..
199 error Windows_NT 6.1.7601
200 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "ng2-my-datepicker" "--save"
201 error node v5.11.1
202 error npm  v3.8.6
203 error code ELIFECYCLE
204 error ng2-my-datepicker@0.1.1 postinstall: `typings install`
204 error Exit status 1
205 error Failed at the ng2-my-datepicker@0.1.1 postinstall script 'typings install'.

**Comment by morocarlo** [comment]
install typings:

npm install typings -g

**Comment by JacosNet** [comment]
Thanks for feedback, it's working now, typings was not installed globally
